[package]
name = "dolos"
version = "0.1.0"
edition = "2021"
authors = ["benetis <git@benetis.me>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = "0.6"
regex = "= 1.9.6"